### ISSUE TITLE
Temperature Sensor Pin Order on PCB

### ISSUE THREAD

**Issue by p0ttsworth** [lbussy/brew-bubbles#33]
More of a suggestion than an issue, please feel free to close if not appropriate place to raise.

Could the order of the temp sensor pads on the PCB be changed to Gnd, Data, Vcc so that a integrated / lead-less  18d20 can be used for the room sensor?

**Comment by p0ttsworth** [comment]
Edit - sorry just saw the thread on home brew talk where you explained why you didn't do this. 

Sorry for the spam!

**Comment by lbussy** [comment]
No worries (and not sure why I did not get a notice for this.)

**Comment by lbussy** [comment]
Going to pin this one for a while.  The explanation was [posted on HBT](https://www.homebrewtalk.com/threads/brew-bubbles-web-enabled-airlock.673559/page-3#post-8837398).  Briefly:

- The pin order is the same as the psedo-standard for BrewPi.
- A DS18B20 directly on the board was tested for this project. It ran almost 10°F hotter due to the heat from the chip.  The reason iSpindel can get away with it is that it's in deep sleep mode in between transmissions and therefore not heating. Since this is meant to be accessed all of the time, that was not an option.
